---
- name: File Module
  hosts: all

  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: touch
      owner: joakim
      group: joakim
      mode: u=rwx,g=rw,o=r

  - name: Creating a directory
    file:
      path: /tmp/myfolder
      state: directory