---
- name: Firewall changes
  hosts: all
  become: true            # sudo with playbook

  tasks:
  - name: Enable a service in firewalldd
    firewalld:
      port: 80/tcp
      permanent: true
      state: disabled
    notify: 
      - Reload firewalld

  handlers:
  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded

